### ISSUE TITLE
cannot import name '_get_trace_graph'

### ISSUE THREAD

**Issue by jiku100** [stevewongv/InstanceShadowDetection#11]
I use your docker image by nvidia-docker and follow your README to run demo.py
but i got "cannot import name '_get_trace_graph' error" in running
"python demo.py --input ./demo/web-shadow0573.jpg --output ./ --config ./config/LISA_101_FPN_3x_demo.yaml"

How can i solve this?

![Screenshot from 2021-05-11 22-17-40](https://user-images.githubusercontent.com/60598554/117821640-be2f0580-b2a6-11eb-867c-14d9de2e6762.png)

**Comment by stevewongv** [comment]
Could you send me more information like the env settings? It will help me investigate this issue.

**Comment by jiku100** [comment]
> Could you send me more information like the env settings? It will help me investigate this issue.

I used your docker image, So it will be the same as you.

OS: Ubuntu 18.04
CUDA: 10.0
Graphic card: gtx 1060
python: 3.6.9
torch: 1.3.0+cu100
torchvision: 0.4.1+cu100
tensorboard: 2.5.0
cython: 0.29.23
skimage: 0.17.2
cv2: 4.5.2
fvcore: 0.1.5

In my searching, Maybe fvcore could be the cause of the problem.

**Comment by stevewongv** [comment]
Yes, the problem is caused by fvcore. You can try old version like 0.1.3.

**Comment by jiku100** [comment]
> Yes, the problem is caused by fvcore. You can try old version like 0.1.3.

How can i downgrade fvcore?

**Comment by jiku100** [comment]
> Yes, the problem is caused by fvcore. You can try old version like 0.1.3.

I can solve that problem by using fvcore version 0.1.2. Thanks!!
but, I get another errors. please help me..
![Screenshot from 2021-05-12 10-56-56](https://user-images.githubusercontent.com/60598554/117907040-084cd100-b311-11eb-86d8-747991692b6a.png)

**Comment by stevewongv** [comment]
Check the pretrained model?

**Comment by jiku100** [comment]
> Check the pretrained model?

Yes, I dowload from your Google Drive and put the model in projects/LISA/output_light/

**Comment by stevewongv** [comment]
I cannot reproduce this error in my docker. Could you recheck the pth file or download it again?

**Comment by jiku100** [comment]
> I cannot reproduce this error in my docker. Could you recheck the pth file or download it again?

Without any other changes, can I just put last_checkpoint.pth and model_final.pth in output_light?

**Comment by stevewongv** [comment]
Yes actually.

**Comment by jiku100** [comment]
> Yes actually.

Oh, After I rebuilded the setup.py files, then it works!! 
Thanks a lot!!
