### ISSUE TITLE
Can I get your SOBA data set

### ISSUE THREAD

**Issue by tall2sad** [stevewongv/InstanceShadowDetection#13]

**Comment by stevewongv** [comment]
https://drive.google.com/drive/folders/1MKxyq3R6AUeyLai9i9XWzG2C_n5f0ppP

**Comment by aviadmx** [comment]
<img width="412" alt="image" src="https://github.com/stevewongv/InstanceShadowDetection/assets/95345571/8ae174cd-4057-459c-a69a-872635b8037a">
@stevewongv 
Has anything changed in the google drive permissions?
