### ISSUE TITLE
Upgrade to Pytorch 1.8

### ISSUE THREAD

**Issue by legnaib** [stevewongv/InstanceShadowDetection#14]
Is there a version available which works with an updated version of pytorch or with a current version of detectron2? Any help is appreciated!

Currently I get the following error while installing the package:

In file included from /home/appuser/ISD/detectron2/layers/csrc/vision.cpp:2:0:
    /home/appuser/ISD/detectron2/layers/csrc/ROIAlign/ROIAlign.h: In function 'at::Tensor ROIAlign_forward(const at::Tensor&, const at::Tensor&, float, int, int, int, bool)':
    /home/appuser/ISD/detectron2/layers/csrc/ROIAlign/ROIAlign.h:60:18: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
       if (input.type().is_cuda()) {
                      ^

**Comment by stevewongv** [comment]
I will try to upgrade this work to support new version detectron2 and Pytorch 1.8 before Sept. And you may try our new work: https://github.com/stevewongv/SSIS

**Comment by legnaib** [comment]
Thanks for your fast reply! I will definitely have a look into your new work, that sounds really impressive and promising!

**Comment by legnaib** [comment]
I tested out the other repo (SSIS) and everything worked smoothly, you really saved my day! By the way, you are not providing any LICENSE-file, it would be nice if you can add that. Probably you're using the same license as detectron2 - namely Apache, right?

**Comment by stevewongv** [comment]
Thank you for reminding me about this! Yes, it uses the same license as Detectron2. I will add it now!

**Comment by RostyslavBryiovskyi** [comment]
> I will try to upgrade this work to support new version detectron2 and Pytorch 1.8 before Sept. And you may try our new work: https://github.com/stevewongv/SSIS

Any update about this ?)
torch 1.3.0, 1.4.0., 1.5.0 have problems with allocating tensors on gpu

**Comment by stevewongv** [comment]
Cloud you send me the error message?

**Comment by stevewongv** [comment]
I will try this on the latest version of the PyTorch tomorrow. ( it's late night) Thanks for your report!

**Comment by RostyslavBryiovskyi** [comment]
I can allocate tensor on GPU with torch 1.10.2+cu11.3. But with this version I encountered some problems during build

**Comment by RostyslavBryiovskyi** [comment]
Hi, @stevewongv 

Do you have any updates ?

**Comment by stevewongv** [comment]
I have updated the repo to support latest version of PyTorch. But I need to retrain it to check whether the performance will be affected by the changes. Stay tuned! Also, I'm working on rebuttal for some conference. So maybe I will update the results after the rebuttal period. Thanks for your report! You can try the demo, or wait me for a few days.

**Comment by RostyslavBryiovskyi** [comment]
@stevewongv ,Thank you!
I have tested demo, and it works perfect!

**Comment by stevewongv** [comment]
Thanks for your report and patience!
