### ISSUE TITLE
Clarification on SOBA statistics

### ISSUE THREAD

**Issue by kiraicode** [stevewongv/InstanceShadowDetection#17]
Hi, great project! 

I'm going through your paper and generating statistics for the SOBA dataset. However, I cannot figure out how you compute the proportion of image space occupied by shadow/object instances (right histogram, figure 3). 

By proportion of image space on the "horizontal axis," do you mean something like: `box_width / img_width`? 

Do you have the code so I can take a look?

I really appreciate any help you can provide. Thanks!

**Comment by stevewongv** [comment]
Thank you for your interest! You just can compute the number of pixels which are not zero in shadow mask/ object instance mask. Like 
```python
# assume we get the object_instance_mask from pysobatool, its size is (800,480)
object_instance_pixels = object_instance_mask > 0 # if it is not a binary mask, then we convert it to binary mask
object_instance_number_of_pixels = object_instance_pixels.sum()
object_instance_proportion = object_instance_number_of_pixels / (800*480)
```

**Comment by kiraicode** [comment]
Thanks for the response! That's helpful. I have been using the "area" given in each instance annotation. 

Perhaps I'm doing a mistake in how I count them. For example, let's assume we try to find the percentage of images that contain object instances with less than 1% proportion of image space. 

This is my approach:

Suppose we have the list `img_ratios` where each element is a list of `object_instance_proportion` corresponding to each object instance in an image. So `img_ratios` has a length of 1000 and each element's length is `n`, for the `n` number of object instances for that image.

For a single image:
```python
count = 0 # keep track of the number of images meeting the criteria

threshold = 0.01 # we're filtering for object instances that occupy less than or equal to 1% of image space
ratios = img_ratios[0] # grab the first element in the list, let's assume it's the first image
filtered_ratios = (ratios <= threshold) # we know how many instances occupy less than 1% image space

# if we found at least one instance that meets the criteria
# we count that image as having <= 1% object instances 
if np.any(filtered_ratios):  
    count += 1
``` 

Then I put this on a for-loop. Lastly, I have the number of images that have at least one object instance taking less than 1% of image space. Then I do `count/1000` to get that percentage. My numbers seem pretty off.

I felt this should be a simple thing in comparison to the whole paper but it's been driving making me scratch my head! 

Thanks again for the help!
