### ISSUE TITLE
where did you define proposal_per_image? 

### ISSUE THREAD

**Issue by I3aer** [stevewongv/InstanceShadowDetection#18]
https://github.com/stevewongv/InstanceShadowDetection/blob/1b75e94394ec0abb8cb39820d6311994efca27cf/projects/LISA/LISA/LISA_rcnn.py#L228

**Comment by stevewongv** [comment]
Do you mean this one?
 https://github.com/stevewongv/InstanceShadowDetection/blob/1b75e94394ec0abb8cb39820d6311994efca27cf/projects/LISA/LISA/LISA_rcnn.py#L175
