### ISSUE TITLE
ImportError: cannot import name '_C' from 'detectron2'

### ISSUE THREAD

**Issue by Eooming** [stevewongv/InstanceShadowDetection#2]
Hello,
There are some problem when I run demo.py.

File "/home/ftl/code/InstanceShadowDetection-master/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: cannot import name '_C' from 'detectron2' (/home/ftl/code/InstanceShadowDetection-master/detectron2/__init__.py)

Could you give me some advice?

Regards.

**Comment by xiexiaozheng** [comment]
$ cd InstanceShadowDetection
$ python setup.py install
$ cd PythonAPI
$ python setup.py install

**Comment by Eooming** [comment]
Thanks a lot.
Acutally, I've solved the above question. Now, there are some new problems. The problem is shown below:

'RuntimeError: Not compiled with GPU support (ROIAlign_forward at ...)' 

1. I didn't run the commands in 'Docker', which has the flag '--gpus'. I wonder if this is the cause of the problem.
2. I wonder if the commands in Docker are necessary. That is, is there a way to specify the GPU without running commands in 'Docker'.

Thanks again~

Regards.

**Comment by devshree07** [comment]
@Eooming How did you solve the below error?
File "/home/ftl/code/InstanceShadowDetection-master/detectron2/layers/deform_conv.py", line 10, in
from detectron2 import _C
ImportError: cannot import name '_C' from 'detectron2' (/home/ftl/code/InstanceShadowDetection-master/detectron2/init.py)

**Comment by devshree07** [comment]
Can you help me solve this error?
ImportError: /usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
@Eooming @xiexiaozheng

**Comment by Eooming** [comment]
You can try like this:

1. remove two folder 'build' in InstanceShadowDetection/ and InstanceShadowDetection/PythonAPI/

2. retry the following.
$ cd InstanceShadowDetection
$ python setup.py install
$ cd PythonAPI
$ python setup.py install

**Comment by stevewongv** [comment]
@Eooming  Thank you for your helping and suggestions!

**Comment by devshree07** [comment]
I am still getting the same error after following the aforementioned steps by you @Eooming @stevewongv

**Comment by stevewongv** [comment]
Have you @devshree07  ever tried using a virtual environment (eg. virtualenv) to run code? You can try it with following commands:
```
$ virtualenv --no-site-packages -p python3.6 py3.6
$ source ./py3.6/bin/activate
$ pip install  tensorboard cython jupyter scikit-image numpy opencv-python
$ pip install torch==1.3.0+cu100 torchvision==0.4.1+cu100 -f https://download.pytorch.org/whl/torch_stable.html
$ pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
$ pip install 'git+https://github.com/facebookresearch/fvcore'
$ cd InstanceShadowDetection
$ python setup.py install
$ cd PythonAPI
$ python setup.py install
```

**Comment by Eooming** [comment]
Hi,@stevewongv

There is a problem when I run demo.py.

After 'python demo.py --input ./demo/web-shadow0573.jpg --output ./ --config ./config/LISA_101_FPN_3x_demo.yaml'. The result shows as below.

"Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    predictions, visualized_output = demo.run_on_image(img)
  File "/home/ISD/InstanceShadowDetection/projects/LISA/predictor.py", line 47, in run_on_image
    predictions = self.predictor(image)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/engine/defaults.py", line 176, in __call__
    predictions = self.model([inputs])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ISD/InstanceShadowDetection/projects/LISA/LISA/LISA_meta_arch.py", line 29, in forward
    return self.inference(batched_inputs)
  File "/home/ISD/InstanceShadowDetection/projects/LISA/LISA/LISA_meta_arch.py", line 84, in inference
    results,associations, _ = self.roi_heads(images, features, association_proposals, proposals, None, None)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ISD/InstanceShadowDetection/projects/LISA/LISA/LISA_rcnn.py", line 90, in forward
    pred_instances = self._forward_box(features_list, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 590, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/modeling/poolers.py", line 195, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /data/InstanceShadowDetection/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:359)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f570b8a3813 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0xa24 (0x7f5704a0f3a0 in /usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0xb6 (0x7f57049cfef6 in /usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x4271b (0x7f57049e171b in /usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x3bab0 (0x7f57049daab0 in /usr/local/lib/python3.6/dist-packages/detectron2-0.1-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: python() [0x50a7f5]
<omitting python frames>
frame #7: python() [0x507f24]
frame #8: python() [0x588ddb]
frame #10: THPFunction_apply(_object*, _object*) + 0xa4f (0x7f56fcbe620f in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #11: python() [0x50a47f]
frame #14: python() [0x594b01]
frame #17: python() [0x507f24]
frame #19: python() [0x594b01]
frame #20: python() [0x54ac61]
frame #22: python() [0x50a783]
frame #25: python() [0x594b01]
frame #28: python() [0x507f24]
frame #30: python() [0x594b01]
frame #31: python() [0x54ac61]
frame #33: python() [0x50a783]
frame #35: python() [0x509918]
frame #36: python() [0x50a64d]
frame #38: python() [0x507f24]
frame #40: python() [0x594b01]
frame #43: python() [0x507f24]
frame #45: python() [0x594b01]
frame #46: python() [0x54ac61]
frame #48: python() [0x50a783]
frame #50: python() [0x507f24]
frame #51: python() [0x509c50]
frame #52: python() [0x50a64d]
frame #54: python() [0x507f24]
frame #56: python() [0x594b01]
frame #59: python() [0x507f24]
frame #61: python() [0x594b01]
frame #62: python() [0x54ac61]"

Can you help me with this~

Regards.

**Comment by Eooming** [comment]
Thanks.

According to your link. One of the reason is that 'You build detectron2 with one version of CUDA but run it with a different version.' As the detectron2 is pre-built by you, I want to know the version of CUDA when you built detectron2.

By the way, it seems that you have changed the code. The output of **python -m detectron2.utils.collect_env** is shown as below, which is lack of 'Detectron2 CUDA Compiler' and 'CUDA_HOME'.

---------------------  -------------------------------------------------------------------------------
Python                 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42) [GCC 7.5.0]
Detectron2 Compiler    GCC 5.4
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.3.0+cu100
PyTorch Debug Build    False
CUDA available         True
GPU 0,1,2,3            GeForce RTX 2080 Ti
Pillow                 7.2.0
cv2                    4.4.0
---------------------  -------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by Eooming** [comment]
Could you show us your Dependencies when tested this code? The version of cuda, cudnn and other stuff. Thanks

**Comment by stevewongv** [comment]
Thank you for your advice. I will add dependences in the README. The version of CUDA is 10.0.
