### ISSUE TITLE
Number of categories

### ISSUE THREAD

**Issue by RostyslavBryiovskyi** [stevewongv/InstanceShadowDetection#21]
Hello, @stevewongv 
Correct me, if I'm wrong. We have only 2 categories, that model could recognize: object and object`s shadow. Model doesn't recognize object by specific categories like persons, cars, dogs, etc. And in case we don't have any shadow on image, but object (person, for example) present, we don't get any predictions at all.

**Comment by stevewongv** [comment]
You are right. We only recognize the object instances whose shadows are in the image. And we only have two classes: object and shadow.
