### ISSUE TITLE
Error Running setup.py

### ISSUE THREAD

**Issue by qyangaa** [stevewongv/InstanceShadowDetection#4]
Hi,

I encountered error when running setup.py in InstanceShadowDetection/. The error message I saw was:
`error: command 'gcc' failed with exit status 1`
In traceback I saw
`/InstanceShadowDetection/detectron2/layers/csrc/deformable/deform_conv.h:339:5: error: ‘AT_CHECK’ was not declared in this scope
     AT_CHECK(input.type().is_cuda(), "input tensor is not on GPU!");`

and a note:
`/home/arky/files/background_switch/InstanceShadowDetection/detectron2/layers/csrc/deformable/deform_conv.h:339:5: note: suggested alternative: ‘DCHECK’
     AT_CHECK(input.type().is_cuda(), "input tensor is not on GPU!");
     ^~~~~~~~
     DCHECK
`
It seems that it is from the detectron package but the detectron2 package has updated them to TORCH_CHECK. Not sure what the problem was.

Thank you for sharing this work!

**Comment by stevewongv** [comment]
Do you solve the problem? if not, you can try [virtual environment](https://github.com/stevewongv/InstanceShadowDetection/issues/2#issuecomment-689945449).
