### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:359)

### ISSUE THREAD

**Issue by realgump** [stevewongv/InstanceShadowDetection#5]
Hi, I have successfully run the demo.py in the xshell terminal of a remote server. However, when I use pycharm to debug, there is a error occurs:

CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:359)

I have no idea about that. Could you plz give me some suggestion? I didn't use Docker to set the environment. My pytorch version is **py3.6_cuda10.0.130_cudnn7.6.3_0**, my cuda has 3 versions of 10.0, 10.1 and 11.1 and I set the version **10.0** in the .bashrc and pycharm configrations. My gpu is Nvidia 2080ti * 4.

你好，我在远程服务器的xshell可以正常运行demo文件。但是当我用pycharm连接服务器远程调试的时候出现了如下报错，

CUDA error: no kernel image is available for execution on the device (ROIAlign_forward_cuda at /detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:359)

我查阅了相关资料没有找到出现问题的原因。我没用docker， 直接手动安装了环境。我的pytorch版本是py3.6_cuda10.0.130_cudnn7.6.3_0，我的cuda安装了三个版本，我修改了bashrc里面的环境变量和pycharm运行时的环境变量，但是仍然跑不通。我的显卡是4块2080Ti。

**Comment by Boristype000** [comment]
Same issue here.

**Comment by stevewongv** [comment]
建议重新强制编译代码
