### ISSUE TITLE
Run a pre-trained model

### ISSUE THREAD

**Issue by annam98** [stevewongv/InstanceShadowDetection#6]
Hey, 
is it possible to run a pre-trained model like they did it in detectron2? link to how they did it: 
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=dq9GY37ml1kr
and it worked perfectly fine for me when running just on Windows (no need for cuda, linux or WSL)

I don't need to train the data, just want to run the model on my pictures.
Hope you can help me

**Comment by stevewongv** [comment]
You can try our latest work on https://colab.research.google.com/drive/1y9UpS5uA1YuoMyvYVzcKL4ltA_FDu_x0?usp=sharing
