### ISSUE TITLE
rendering  shadow with light direction

### ISSUE THREAD

**Issue by hy-zpg** [stevewongv/InstanceShadowDetection#8]
Hi, I have successfully run your demo and it's very interesting. I want to know how to render a shadow with the estimated light direction and a virtual object.  Because we don't know the position of the camera, it may be difficult to conduct 3D rendering.

**Comment by stevewongv** [comment]
Hi! As mention in this paper, we can roughly compute the 2D light direction based on the object center and shadow center.
