### ISSUE TITLE
Visualize/compute light prediction

### ISSUE THREAD

**Issue by mcleanalec** [stevewongv/InstanceShadowDetection#9]
It's not clear within the code how to compute/visualize the light direction. How do you do that? 

From the output I can see `pred_boxes` and `pred_light`. The units of `pred_light` are not clear - I can see from the paper/code you use the [atan2 function](https://pytorch.org/docs/stable/generated/torch.atan2.html) but I am not sure how to use those units. Can you elaborate, please?

**Comment by stevewongv** [comment]
As mention in the paper, we roughly compute the 2D light direction based on the center of object and shadow. This is more accurate than the Pred_light, which only helps network to find the associations.
